### ISSUE TITLE
Paste Layer Gerbers

### ISSUE THREAD

**Issue by cdd3** [jakplugg/uO_c#2]
Would it be possible to publish the cream layer gerbers for making stencils?

**Comment by jakplugg** [comment]
Sorry, but the diptrace file has had minor tweaks since then, so they would be wrong, hopefully some time next week ill release the new uo_c version (with supervisor teensy boot option), all the newer gerbers i upload have the paste layer.

**Comment by cdd3** [comment]
Awesome, Thanks!

**Comment by wardour** [comment]
Just wanted to jump on this, and say I'm looking forward to the new design with paste file available.

**Comment by jakplugg** [comment]
so sorry i took so long with that, "put on google drive" does not equal uploaded to github!

**Comment by cdd3** [comment]
Thanks so much. Really appreciate the work you've been up to!
